# Generated by Django 4.2.23 on 2025-06-27 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('initial_count', models.PositiveIntegerField()),
                ('acquisition_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item', models.CharField(choices=[('Eggs', 'Eggs'), ('Chicken', 'Chicken')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='flock.flock')),
            ],
        ),
        migrations.CreateModel(
            name='MortalityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortality_logs', to='flock.flock')),
            ],
        ),
        migrations.CreateModel(
            name='FeedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity_kg', models.FloatField()),
                ('cost', models.FloatField()),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_logs', to='flock.flock')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='flock.flock')),
            ],
        ),
        migrations.CreateModel(
            name='EggLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField()),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egg_logs', to='flock.flock')),
            ],
        ),
    ]
